### ISSUE TITLE
Error in Google Chrome

### ISSUE THREAD

**Issue by SeasideMedia** [fourroses666/responsive-preview#1]
Hello,

when i use this in Google Chrome the script redirect to the site is in the Iframe from the index.html

Best regards
Joachim

**Comment by fourroses666** [comment]
Looks like there are issues with the default page that is loaded.
When you type a new URL it works right?

You can change the index file:
`<iframe id="iframe" src="http://www.graffx.nl" width="100%"></iframe>`

Change the src="http://www.graffx.nl" to whatever you like.
Does that fix your issue?

**Comment by SeasideMedia** [comment]
Hello,

first thank you for the quick respons, no the problem is also. Look here at
http://www.seaside-media.com/responsive-check/ i have there in the Frame a
site from my wordpress blog. The site in the Frame is
http://www.seaside-media.com/testen-sie-ihre-webseite-mit-unserem-responsive-checker-tool/

That works perfect in the Firefox Browser, in the IE works perfect but with
Chrome i have a redirect from the site
http://www.seaside-media.com/responsive-check/ to the site into the frame
http://www.seaside-media.com/testen-sie-ihre-webseite-mit-unserem-responsive-checker-tool/

Best regards

Mit freundlichen Grüßen

Joachim Paul

_Seaside Media Webdesign_

Inhaber: Joachim Paul
Heidelbergerstrasse 55/1

74821 Mosbach

Telefon:  06261 / 180 72 36

E-Mail:    joachim@seaside-media.de
Internet:  _www.seaside-media.de http://www.seaside-media.de/_

_Hinweis zum Datenschutz:_

Der Inhalt dieser E-Mail sowie etwaiger Anlagen hierzu sind vertraulich und
ausschließlich für den Gebrauch durch den Empfänger bestimmt. Soweit eine
Weitergabe oder Verteilung nicht ausschließlich zu internen Zwecken des
Empfängers geschieht, wird jede Weitergabe, Verteilung oder sonstige Kopie
untersagt. Sollten Sie nicht der beabsichtigte Empfänger der E-Mail sein,
löschen Sie bitte diese E-Mail und informieren Sie bitte den Absender
unverzüglich.

Wir weisen Sie darauf hin, dass mit der Versendung von Daten per E-Mail das
Risiko nicht ausgeschlossen werden kann, dass der Inhalt von fremden
Dritten eingesehen, ausgewertet oder gar verändert weitergeleitet wird.
Wenn Sie nicht damit einverstanden sind, dass vertrauliche Daten per E-Mail
an Sie verschickt werden, möchten wir Sie bitten, uns davon in Kenntnis zu
setzen.

_Sicherheitshinweis:_

Trotz aktueller Sicherheitsprüfungen, die dieses e-Mail durchlaufen hat,
wird eine Haftung ausgeschlossen, falls Computer-Viren mit der Mail
übertragen wurden.

2015-10-22 10:19 GMT+02:00 Marc notifications@github.com:

**Comment by fourroses666** [comment]
It works with me in Chrome Win7, is it a cache issue?

**Comment by SeasideMedia** [comment]
Hmm i test this site http://www.seaside-media.com/responsive-check/ with 3
different PC in Chrome and have all time the same error that the site
redirect to this site
http://www.seaside-media.com/testen-sie-ihre-webseite-mit-unserem-responsive-checker-tool/

You go on this site http://www.seaside-media.com/responsive-check/ and have
no redirect to the site in the Iframe?

Best regards.
Joachim

Mit freundlichen Grüßen

Joachim Paul

_Seaside Media Webdesign_

Inhaber: Joachim Paul
Heidelbergerstrasse 55/1

74821 Mosbach

Telefon:  06261 / 180 72 36

E-Mail:    joachim@seaside-media.de
Internet:  _www.seaside-media.de http://www.seaside-media.de/_

_Hinweis zum Datenschutz:_

Der Inhalt dieser E-Mail sowie etwaiger Anlagen hierzu sind vertraulich und
ausschließlich für den Gebrauch durch den Empfänger bestimmt. Soweit eine
Weitergabe oder Verteilung nicht ausschließlich zu internen Zwecken des
Empfängers geschieht, wird jede Weitergabe, Verteilung oder sonstige Kopie
untersagt. Sollten Sie nicht der beabsichtigte Empfänger der E-Mail sein,
löschen Sie bitte diese E-Mail und informieren Sie bitte den Absender
unverzüglich.

Wir weisen Sie darauf hin, dass mit der Versendung von Daten per E-Mail das
Risiko nicht ausgeschlossen werden kann, dass der Inhalt von fremden
Dritten eingesehen, ausgewertet oder gar verändert weitergeleitet wird.
Wenn Sie nicht damit einverstanden sind, dass vertrauliche Daten per E-Mail
an Sie verschickt werden, möchten wir Sie bitten, uns davon in Kenntnis zu
setzen.

_Sicherheitshinweis:_

Trotz aktueller Sicherheitsprüfungen, die dieses e-Mail durchlaufen hat,
wird eine Haftung ausgeschlossen, falls Computer-Viren mit der Mail
übertragen wurden.

2015-10-22 11:50 GMT+02:00 Marc notifications@github.com:

**Comment by fourroses666** [comment]
I have no error / issues with the iframe URL. The responsive script loads this URL:
http://www.seaside-media.com/testen-sie-ihre-webseite-mit-unserem-responsive-checker-tool/
in Firefox , IE and in Chrome.

Did you clear your cookies or flush DNS?
Maybe you can ask someone else who has Chrome?

---

There are a couple of not found styles by the way:
http://www.seaside-media.com/assets/css/style-items.css Failed to load resource: the server responded with a status of 404 (Not Found)
2http://www.seaside-media.com/assets/css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://www.seaside-media.com/assets/css/style-items.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by SeasideMedia** [comment]
I have now install the script on my other site http://www.seaside-media.de/responsive-check/ and here is the same problem with the crome browser.

But i ask a friend and he have not this redirect. OK so it is only a problem on my browser.

Thank you very much for your support

**Comment by fourroses666** [comment]
No problem, if you have any issues or questions just let me know.

I had some issues this morning when looking at my own site with this responsive test script.
Seems that issues where because the page loading in the iframe was being attacked by a DDOS attack lol. 

---

ah the not found css styles are being called here: 
https://github.com/fourroses666/responsive-preview/blob/master/responsive/responsive/js/init.js
